/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually


  mobileSDKs: [
    {
      type: 'category',
      label: 'Idenfo - Platform Overview',
      items: [
        'intro',
        'features',
        'flow',
        // {
        //   type: 'category',
        //   label: 'Platforms',
        //   items: ['platforms/ios', 'platforms/android'], // Ensure these paths match your docs
        // },
        // {
        //   type: 'category',
        //   label: 'Getting Started',
        //   items: ['parameters/presets', 'parameters/responses', 'parameters/secure', 'parameters/generateApiKeys'], // Ensure these paths match your docs
        // },
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'parameters/presets',
        'parameters/responses',
        'parameters/secure',
        'parameters/generateApiKeys'
        // {
        //   type: 'category',
        //   label: 'Getting Started',
        //   items: ['parameters/presets', 'parameters/responses', 'parameters/secure', 'parameters/generateApiKeys'], // Ensure these paths match your docs
        // },
      ],
    },
    {
      type: 'category',
      label: 'SDK Integration',

      items: [
        'platforms/ios',
        'platforms/android',
        'platforms/customize'
        // {
        //   type: 'category',
        //   label: 'Getting Started',
        //   items: ['parameters/presets', 'parameters/responses', 'parameters/secure', 'parameters/generateApiKeys'], // Ensure these paths match your docs
        // },
      ],
    },
  ],
  restfulApiSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],

};

export default sidebars;
